CREATE TABLE IF NOT EXISTS USERS(id INTEGER, name VARCHAR(256), email VARCHAR(256), address VARCHAR(256), birthdate DATE,
    socialNumber CHAR(12), ccard CHAR(16), post_code VARCHAR(20))   ;

CREATE TABLE IF NOT EXISTS COMPANIES(id INTEGER, name VARCHAR(256), address VARCHAR(256));